stages:
  - build

build:docker:
  stage: build
  image: docker:17.06.2-ce
  script:
    - apk add --no-cache make git wget bash groff less python py-pip
    - pip install awscli
    - export AWS_DEFAULT_REGION=ap-southeast-2
    - make
  only:
    - trigger
    - master
  tags:
    - full360
