name: JRuby 1.7 Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  jruby-17:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 1.7 JRE 7
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/1.7/jre
        file: ./jruby/1.7/jre/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:1.7-jre
          full360/jruby:1.7-jre7

    - name: Build JRuby 1.7 JRE 7 on-build
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/1.7/jre-onbuild
        file: ./jruby/1.7/jre-onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:1.7-jre-onbuild
          full360/jruby:1.7-jre7-onbuild
