name: JRuby 1.7 Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 0

jobs:
  jruby-17:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/1.7/jre
        always_pull: true
        repository: full360/jruby
        tags: 1.7-jre,1.7-jre7

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/1.7/jre-onbuild
        always_pull: true
        repository: full360/jruby
        tags: 1.7-jre-onbuild,1.7-jre7-onbuild
