name: JRuby 9000 Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  jruby-91-jre7:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 9.1 JRE 7
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.1/jre7
        file: ./jruby/9.1/jre7/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9.1-jre7

    - name: Build JRuby 9.1 JRE 7 on-build
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.1/jre7/onbuild
        file: ./jruby/9.1/jre7/onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9.1-jre7

  jruby-91-jre8:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 9.1 JRE 8 Alpine
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.1/jre8
        file: ./jruby/9.1/jre8/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9.1-jre-alpine
          full360/jruby:9.1-jre8-alpine

    - name: Build JRuby 9.1 JRE 8 Alpine on-build
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.1/jre8/onbuild
        file: ./jruby/9.1/jre8/onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9.1-jre-alpine-onbuild
          full360/jruby:9.1-jre8-alpine-onbuild

  jruby-92-jre8:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 9.2 JRE 8
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.2/jre8
        file: ./jruby/9.2/jre8/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9-jre8
          full360/jruby:9.2-jre8

    - name: Build JRuby 9.2 JRE 8 on-build
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.2/jre8/onbuild
        file: ./jruby/9.2/jre8/onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9-jre8-onbuild
          full360/jruby:9.2-jre8-onbuild

  jruby-92-jre11:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build JRuby 9.2 JRE 11
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.2/jre11
        file: ./jruby/9.2/jre11/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:latest
          full360/jruby:9-jre11
          full360/jruby:9.2-jre11

    - name: Build JRuby 9.2 JRE 11 on-build
      uses: docker/build-push-action@v2
      with:
        context: ./jruby/9.2/jre11/onbuild
        file: ./jruby/9.2/jre11/onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/jruby:9-jre11-onbuild
          full360/jruby:9.2-jre11-onbuild
