name: JRuby 9000 Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  jruby-91-jre7:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.1/jre7
        always_pull: true
        repository: full360/jruby
        tags: 9.1-jre7

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.1/jre7/onbuild
        always_pull: true
        repository: full360/jruby
        tags: 9.1-jre7-onbuild

  jruby-91-jre8:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.1/jre8
        always_pull: true
        repository: full360/jruby
        tags: 9.1-jre-alpine,9.1-jre8-alpine

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.1/jre8/onbuild
        always_pull: true
        repository: full360/jruby
        tags: 9.1-jre-alpine-onbuild,9.1-jre8-alpine-onbuild

  jruby-92-jre8:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.2/jre8
        always_pull: true
        repository: full360/jruby
        tags: 9-jre8,9.2-jre8

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.2/jre8/onbuild
        always_pull: true
        repository: full360/jruby
        tags: 9-jre8-onbuild,9.2-jre8-onbuild

  jruby-92-jre11:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.2/jre11
        always_pull: true
        repository: full360/jruby
        tags: latest,9-jre11,9.2-jre11

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: jruby/9.2/jre11/onbuild
        always_pull: true
        repository: full360/jruby
        tags: 9-jre11-onbuild,9.2-jre11-onbuild
