name: Ruby 2.x Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  ruby-26:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Ruby 2.6 Alpine
      uses: docker/build-push-action@v2
      with:
        context: ./ruby/2.6/alpine
        file: ./ruby/2.6/alpine/Dockerfile
        pull: true
        push: true
        tags: |
          full360/ruby:latest
          full360/ruby:2-alpine
          full360/ruby:2.6-alpine

    - name: Build Ruby 2.6 Alpine onbuild
      uses: docker/build-push-action@v2
      with:
        context: ./ruby/2.6/alpine/onbuild
        file: ./ruby/2.6/alpine/onbuild/Dockerfile
        pull: true
        push: true
        tags: |
          full360/ruby:2-alpine-onbuild
          full360/ruby:2.6-alpine-onbuild
