name: Ruby 2.x Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  ruby-26:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ruby/2.6/alpine
        always_pull: true
        repository: full360/ruby
        tags: latest,2-alpine,2.6-alpine

    - name: Build onbuild
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ruby/2.6/alpine/onbuild
        always_pull: true
        repository: full360/ruby
        tags: 2-alpine-onbuild,2.6-alpine-onbuild
