name: GitHub CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - ruby/2.6/alpine/Dockerfile
          - jruby/1.7/jre/Dockerfile
          - jruby/9.1/alpine-jre/Dockerfile
          - jruby/9.2/jre8/Dockerfile
          - jruby/9.2/jre11/Dockerfile

    steps:
    - uses: actions/checkout@v2
    - name: Build base
      run: docker build -< ${{ matrix.dockerfile }}
